<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.2 (Python 3.13.1 on win32)" generated="2025-06-24T21:25:24.539631" rpa="false" schemaversion="5">
<suite id="s1" name="Login" source="C:\Users\Taha\RobotFrameworkE2ETests.OTAI\otaiE2ETest\tests\login.robot">
<test id="s1-t1" name="Test++: Valid login" line="8">
<kw name="Given I Open the Lightence App" owner="navigationStepDefinitions">
<kw name="Given I Open The App" owner="navigationPage">
<kw name="Open Browser" owner="SeleniumLibrary">
<msg time="2025-06-24T21:25:24.834728" level="FAIL">Variable '${LOGIN_URL}' not found.</msg>
<arg>${LOGIN_URL}</arg>
<arg>${browser}</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<status status="FAIL" start="2025-06-24T21:25:24.834179" elapsed="0.000602">Variable '${LOGIN_URL}' not found.</status>
</kw>
<kw name="Maximize Browser Window" owner="SeleniumLibrary">
<doc>Maximizes current browser window.</doc>
<status status="NOT RUN" start="2025-06-24T21:25:24.834926" elapsed="0.000029"/>
</kw>
<status status="FAIL" start="2025-06-24T21:25:24.833621" elapsed="0.001451">Variable '${LOGIN_URL}' not found.</status>
</kw>
<kw name="Then I Login In The App" owner="navigationPage">
<arg>${USEREMAIL}</arg>
<arg>${USERPASSWORD}</arg>
<status status="NOT RUN" start="2025-06-24T21:25:24.835216" elapsed="0.000030"/>
</kw>
<status status="FAIL" start="2025-06-24T21:25:24.833274" elapsed="0.002062">Variable '${LOGIN_URL}' not found.</status>
</kw>
<kw name="Sleep" owner="BuiltIn">
<arg>10s</arg>
<doc>Pauses the test executed for the given time.</doc>
<status status="NOT RUN" start="2025-06-24T21:25:24.835856" elapsed="0.000061"/>
</kw>
<kw name="Close Browser" owner="SeleniumLibrary" type="TEARDOWN">
<doc>Closes the current browser.</doc>
<status status="PASS" start="2025-06-24T21:25:24.836285" elapsed="0.000175"/>
</kw>
<tag>LotfiOTAI</tag>
<tag>OTAI</tag>
<tag>Test++</tag>
<status status="FAIL" start="2025-06-24T21:25:24.832516" elapsed="0.004158">Variable '${LOGIN_URL}' not found.</status>
</test>
<status status="FAIL" start="2025-06-24T21:25:24.541177" elapsed="0.296584"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1" skip="0">LotfiOTAI</stat>
<stat pass="0" fail="1" skip="0">OTAI</stat>
<stat pass="0" fail="1" skip="0">Test++</stat>
</tag>
<suite>
<stat name="Login" id="s1" pass="0" fail="1" skip="0">Login</stat>
</suite>
</statistics>
<errors>
<msg time="2025-06-24T21:25:24.827435" level="ERROR">Error in file 'C:\Users\Taha\RobotFrameworkE2ETests.OTAI\otaiE2ETest\utils\fixture.robot' on line 3: Variable file '..\resources\env.py' does not exist.</msg>
</errors>
</robot>
